name: Renew SSL certificate and publish it to www.rec.la

on:
  schedule:
    # each Thursday at 10:30
    - cron:  "30 10 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Fetch dependencies
      run: yarn

    - name: Generate new certificate
      run: IS_PRODUCTION=true GANDI_REC_LA_API_KEY=${{ secrets.GANDI_REC_LA_API_KEY }} yarn start

    - name: Commit and push
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Pryv
        author_email: tech@pryv.com
        # Whether to use the --force option on `git add`, in order to bypass eventual gitignores
        force: false
        message: 'update cert'
